openapi: 3.0.0
info:
  title: License Management Dashboard API - Companies
  version: 1.0.0
  description: Operations related to companies

servers:
  - url: http://localhost:5000
    description: Development server

tags:
  - name: Companies
    description: Operations related to companies

paths:
  /api/companies:
    get:
      summary: Get all companies
      description: Retrieve a list of all companies
      tags:
        - Companies
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of companies
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    address:
                      type: string
                    phone:
                      type: string
                    email:
                      type: string
                    website:
                      type: string
                    createdAt:
                      type: string
                      format: date-time
        '401':
          description: Unauthorized
    post:
      summary: Create a new company
      tags:
        - Companies
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  example: "Example Company Ltd."
                address:
                  type: string
                  example: "123 Business Street, City, Country"
                phone:
                  type: string
                  example: "+1-234-567-8900"
                email:
                  type: string
                  format: email
                  example: "contact@example.com"
                website:
                  type: string
                  format: uri
                  example: "https://www.example.com"
      responses:
        '201':
          description: Created company
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  address:
                    type: string
                  phone:
                    type: string
                  email:
                    type: string
                  website:
                    type: string
                  createdAt:
                    type: string
                    format: date-time
        '401':
          description: Unauthorized
        '400':
          description: Invalid input

  /api/companies/{id}:
    get:
      summary: Get a company by ID
      tags:
        - Companies
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The company ID
      responses:
        '200':
          description: A single company
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  address:
                    type: string
                  phone:
                    type: string
                  email:
                    type: string
                  website:
                    type: string
                  createdAt:
                    type: string
                    format: date-time
        '401':
          description: Unauthorized
        '404':
          description: Company not found
    put:
      summary: Update a company
      tags:
        - Companies
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The company ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Updated Company Name"
                address:
                  type: string
                  example: "456 Updated Street, City, Country"
                phone:
                  type: string
                  example: "+1-987-654-3210"
                email:
                  type: string
                  format: email
                  example: "updated@example.com"
                website:
                  type: string
                  format: uri
                  example: "https://www.updatedcompany.com"
      responses:
        '200':
          description: Updated company
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  address:
                    type: string
                  phone:
                    type: string
                  email:
                    type: string
                  website:
                    type: string
                  createdAt:
                    type: string
                    format: date-time
        '401':
          description: Unauthorized
        '404':
          description: Company not found
    delete:
      summary: Delete a company
      tags:
        - Companies
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The company ID
      responses:
        '204':
          description: Company deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Company not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT