openapi: 3.0.0
info:
  title: License Management Dashboard API - Devices
  version: 1.0.0
  description: Operations related to devices

servers:
  - url: http://localhost:5000
    description: Development server

tags:
  - name: Devices
    description: Operations related to devices

paths:
  /api/devices:
    get:
      summary: Get all devices
      description: Retrieve a list of all devices
      tags:
        - Devices
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of devices
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    licenseId:
                      type: string
                    computerId:
                      type: string
                    name:
                      type: string
                    os:
                      type: string
                    processor:
                      type: string
                    ram:
                      type: integer
                    isActive:
                      type: boolean
                    activatedAt:
                      type: string
                      format: date-time
                    lastSeenAt:
                      type: string
                      format: date-time
        '401':
          description: Unauthorized
    post:
      summary: Create a new device
      tags:
        - Devices
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - licenseId
                - computerId
              properties:
                licenseId:
                  type: string
                  example: license123
                computerId:
                  type: string
                  example: "computer-123456"
                name:
                  type: string
                  example: "My Work Computer"
                os:
                  type: string
                  example: "Windows 10"
                processor:
                  type: string
                  example: "Intel i7"
                ram:
                  type: integer
                  example: 16
                isActive:
                  type: boolean
                  default: true
      responses:
        '201':
          description: Created device
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  licenseId:
                    type: string
                  computerId:
                    type: string
                  name:
                    type: string
                  os:
                    type: string
                  processor:
                    type: string
                  ram:
                    type: integer
                  isActive:
                    type: boolean
                  activatedAt:
                    type: string
                    format: date-time
                  lastSeenAt:
                    type: string
                    format: date-time
        '401':
          description: Unauthorized
        '400':
          description: Invalid input

  /api/devices/{id}:
    get:
      summary: Get a device by ID
      tags:
        - Devices
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The device ID
      responses:
        '200':
          description: A single device
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  licenseId:
                    type: string
                  computerId:
                    type: string
                  name:
                    type: string
                  os:
                    type: string
                  processor:
                    type: string
                  ram:
                    type: integer
                  isActive:
                    type: boolean
                  activatedAt:
                    type: string
                    format: date-time
                  lastSeenAt:
                    type: string
                    format: date-time
        '401':
          description: Unauthorized
        '404':
          description: Device not found
    put:
      summary: Update a device
      tags:
        - Devices
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The device ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Updated Computer Name"
                os:
                  type: string
                  example: "Windows 11"
                processor:
                  type: string
                  example: "Intel i9"
                ram:
                  type: integer
                  example: 32
                isActive:
                  type: boolean
      responses:
        '200':
          description: Updated device
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  licenseId:
                    type: string
                  computerId:
                    type: string
                  name:
                    type: string
                  os:
                    type: string
                  processor:
                    type: string
                  ram:
                    type: integer
                  isActive:
                    type: boolean
                  activatedAt:
                    type: string
                    format: date-time
                  lastSeenAt:
                    type: string
                    format: date-time
        '401':
          description: Unauthorized
        '404':
          description: Device not found
    delete:
      summary: Delete a device
      tags:
        - Devices
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The device ID
      responses:
        '204':
          description: Device deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Device not found

  /api/devices/heartbeat:
    post:
      summary: Device heartbeat
      description: Update last seen time for a device
      tags:
        - Devices
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - licenseKey
                - computerId
              properties:
                licenseKey:
                  type: string
                  example: LIC-12345-ABCDE
                computerId:
                  type: string
                  example: "computer-123456"
      responses:
        '200':
          description: Heartbeat received successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  licenseStatus:
                    type: string
                    enum: [active, expired]
                  message:
                    type: string
        '400':
          description: Missing parameters
        '404':
          description: License or device not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT