openapi: 3.0.0
info:
  title: License Management Dashboard API - Plans
  version: 1.0.0
  description: Operations related to plans

servers:
  - url: http://localhost:5000
    description: Development server

tags:
  - name: Plans
    description: Operations related to plans

paths:
  /api/plans:
    get:
      summary: Get all plans
      tags:
        - Plans
      parameters:
        - in: query
          name: productId
          schema:
            type: string
          required: false
          description: Filter plans by product ID
      responses:
        '200':
          description: A list of plans
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    productId:
                      type: string
                    name:
                      type: string
                    price:
                      type: integer
                    deviceLimit:
                      type: integer
                    durationDays:
                      type: integer
    post:
      summary: Create a new plan
      tags:
        - Plans
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - productId
                - name
                - price
                - deviceLimit
                - durationDays
              properties:
                productId:
                  type: string
                name:
                  type: string
                  example: Basic Plan
                price:
                  type: integer
                  example: 2999
                deviceLimit:
                  type: integer
                  example: 1
                durationDays:
                  type: integer
                  example: 30
      responses:
        '201':
          description: Created plan
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  productId:
                    type: string
                  name:
                    type: string
                  price:
                    type: integer
                  deviceLimit:
                    type: integer
                  durationDays:
                    type: integer
        '401':
          description: Unauthorized
  /api/plans/{id}:
    get:
      summary: Get a plan by ID
      tags:
        - Plans
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The plan ID
      responses:
        '200':
          description: A single plan
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  productId:
                    type: string
                  name:
                    type: string
                  price:
                    type: integer
                  deviceLimit:
                    type: integer
                  durationDays:
                    type: integer
        '404':
          description: Plan not found
    put:
      summary: Update a plan
      tags:
        - Plans
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The plan ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Updated Plan Name
                price:
                  type: integer
                  example: 3999
                deviceLimit:
                  type: integer
                  example: 2
                durationDays:
                  type: integer
                  example: 60
      responses:
        '200':
          description: Updated plan
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  productId:
                    type: string
                  name:
                    type: string
                  price:
                    type: integer
                  deviceLimit:
                    type: integer
                  durationDays:
                    type: integer
        '401':
          description: Unauthorized
        '404':
          description: Plan not found
    delete:
      summary: Delete a plan
      tags:
        - Plans
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The plan ID
      responses:
        '204':
          description: Plan deleted successfully
        '401':
          description: Unauthorized
        '404':
          description: Plan not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT